### ISSUE TITLE
Review classification of paraganglioma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#133]
## http://purl.obolibrary.org/obo/MPATH_403
- **Pr(G)**=0.17705039985121812 CONFIDENCE=0.33333333333333326 Success:true
- **SIZE**=8 (2 new axioms) 
  [img](target/img-MPATH_403.png)
- MEMBER: MPATH_403 paraganglioma
- MEMBER: MPATH_400 carotid body tumor
- MEMBER: NCIT_C3308 Paraganglioma
- MEMBER: NCIT_C3060 Glomus Tumor
- MEMBER: NCIT_C2932 Carotid Body Paraganglioma
- MEMBER: NCIT_C5327 Head and Neck Paraganglioma
- MEMBER: NCIT_C4217 Parasympathetic Paraganglioma
- MEMBER: NCIT_C3309 Extra-Adrenal Paraganglioma
- MPATH_403 paraganglioma EquivalentTo NCIT_C3308 Paraganglioma Pr= 0.85
- MPATH_400 carotid body tumor EquivalentTo NCIT_C2932 Carotid Body Paraganglioma Pr= 0.7

![img-mpath_403](https://cloud.githubusercontent.com/assets/6722114/17565920/34dd7a48-5eee-11e6-9250-775ff18bb25b.png)

**Comment by cmungall** [comment]
here the dashed line represents a *potential* axiom linking classes. However, there is no solid line, so kboom is choosing not to make either a sub, super or equiv axiom. This is because I set the priors for matches made based on related synonyms to be conservative (if an equivalence axiom can be made without inducing unsatisfiability, it will be added, but the next most likely call is no axiom).

For most of these, I think we can safely close the ticket. However, if we want to be diligent we should check the synonyms that lead to a match, possibly file on mpath tracker

**Comment by nicolevasilevsky** [comment]
glomus tumor is a synonym of paraganglioma in MPATH.

I'm not sure why there is the dashed line between MPATH_403 paraganglioma and NCIT_C2932 Carotid Body Paraganglioma though.

**Comment by cmungall** [comment]
> I'm not sure why there is the dashed line between MPATH_403 paraganglioma and NCIT_C2932 Carotid Body Paraganglioma though

shared synonym of chemodectoma
