### ISSUE TITLE
MESH:C538119 Hirschsprung disease ganglioneuroblastoma

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#16]
![hir](https://cloud.githubusercontent.com/assets/50745/8934313/f1fe3c48-34fb-11e5-8ca4-6d13cb5cae6e.png)

**Comment by cmungall** [comment]
underlying cause

```
[Term]
id: Orphanet:2151
name: Hirschsprung disease - ganglioneuroblastoma
xref: ICD-10:Q43.1 {http://purl.obolibrary.org/obo/ECO_0000218="NTBT (narrower term maps to a broader term)"}
xref: MeSH:C538119 {http://purl.obolibrary.org/obo/ECO_0000218="E (exact mapping (the terms and the concepts are equivalent))"}
xref: UMLS:C2751683 {http://purl.obolibrary.org/obo/ECO_0000218="Attributed"}
is_a: Orphanet:377789 ! malformation syndrome
relationship: part_of Orphanet:108969 ! Syndromic intestinal malformation
relationship: part_of Orphanet:117573 ! Syndromic anorectal malformation
```

Should probably be merged with

```
[Term]
id: OMIM:613013
name: Neuroblastoma, Susceptibility To, 2
synonym: "NBLST2" EXACT []
synonym: "NEUROBLASTOMA, SUSCEPTIBILITY TO, 2; NBLST2" EXACT []
synonym: "Neuroblastoma With Hirschsprung Disease" EXACT []
xref: Orphanet:635 !  Neuroblastoma
xref: UMLS:C2751682
xref: UMLS:C2751683

```

however, the xref in OMIM is to a more general class, and the Ordo has no xref.

text mining may fail here due to the qualifier "ganglio" in ORDO

**Comment by pnrobinson** [comment]
Hm, I do not think that Hirschsprung disease ganglioneuroblastoma is a valid disease...

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Chris Mungall [notifications@github.com]
Gesendet: Dienstag, 28. Juli 2015 16:45
An: monarch-initiative/monarch-disease-ontology
Betreff: Re: [monarch-disease-ontology] MESH:C538119 Hirschsprung disease ganglioneuroblastoma (#16)


underlying cause

[Term]
id: Orphanet:2151
name: Hirschsprung disease - ganglioneuroblastoma
xref: ICD-10:Q43.1 {http://purl.obolibrary.org/obo/ECO_0000218="NTBT (narrower term maps to a broader term)"}
xref: MeSH:C538119 {http://purl.obolibrary.org/obo/ECO_0000218="E (exact mapping (the terms and the concepts are equivalent))"}
xref: UMLS:C2751683 {http://purl.obolibrary.org/obo/ECO_0000218="Attributed"}
is_a: Orphanet:377789 ! malformation syndrome
relationship: part_of Orphanet:108969 ! Syndromic intestinal malformation
relationship: part_of Orphanet:117573 ! Syndromic anorectal malformation


Should probably be merged with

[Term]
id: OMIM:613013
name: Neuroblastoma, Susceptibility To, 2
synonym: "NBLST2" EXACT []
synonym: "NEUROBLASTOMA, SUSCEPTIBILITY TO, 2; NBLST2" EXACT []
synonym: "Neuroblastoma With Hirschsprung Disease" EXACT []
xref: Orphanet:635 !  Neuroblastoma
xref: UMLS:C2751682
xref: UMLS:C2751683



however, the xref in OMIM is to a more general class, and the Ordo has no xref.

text mining may fail here due to the qualifier "ganglio" in ORDO

**Comment by cmungall** [comment]
Can you elaborate?

would you agree this is a disease
http://www.omim.org/entry/613013

but the synonyms with neuroblastoma are invalid?

**Comment by pnrobinson** [comment]
The neuroblastoma is a complication of the Hirschsprung, but I do not think it should be listed as a separate disease. If we did that, then we would need to split all known diseases into 100 subtypes each!
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Chris Mungall [notifications@github.com]
Gesendet: Dienstag, 28. Juli 2015 17:12
An: monarch-initiative/monarch-disease-ontology
Cc: Robinson, Peter
Betreff: Re: [monarch-disease-ontology] MESH:C538119 Hirschsprung disease ganglioneuroblastoma (#16)


Can you elaborate?

would you agree this is a disease
http://www.omim.org/entry/613013

but the synonyms with neuroblastoma are invalid?

**Comment by pnrobinson** [comment]
btw note that OMIM is implying they are the same disease while Orphanet is splitting them.

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Chris Mungall [notifications@github.com]
Gesendet: Dienstag, 28. Juli 2015 17:12
An: monarch-initiative/monarch-disease-ontology
Cc: Robinson, Peter
Betreff: Re: [monarch-disease-ontology] MESH:C538119 Hirschsprung disease ganglioneuroblastoma (#16)


Can you elaborate?

would you agree this is a disease
http://www.omim.org/entry/613013

but the synonyms with neuroblastoma are invalid?
