### ISSUE TITLE
Orphanet:98855 is (incorrectly?) equivalent to MESH:D020389

### ISSUE THREAD

**Issue by mwilliamson-healx** [monarch-initiative/monarch-disease-ontology-RETIRED#164]
Monarch seems to consider [Orphanet:98855](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=98855) equivalent to [MESH:D020389](https://www.nlm.nih.gov/cgi/mesh/2016/MB_cgi?exact&field=uid&term=D020389). However, the Orphanet term is "Autosomal recessive Emery-Dreifuss muscular dystrophy", while the MeSH term is "Muscular Dystrophy, Emery-Dreifuss". It seems to me that the correct mapping is that MeSH term to [Orphanet:261](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=261), which is "Emery-Dreifuss muscular dystrophy".

I wonder if this is a specific instance of a more general problem? Specifically, Orphanet explicitly maps both of those Orphanet terms to that MeSH term (as being exactly equivalent). However, I've found that means that Orphanet term is equivalent to the MeSH term *or* one of its entries, which may be narrower than the main term. In this case, D020389 has "Autosomal Recessive Emery-Dreifuss Muscular Dystrophy" as a narrower entry. In other words, perhaps the MeSH-Orphanet mappings cannot be assumed to be exact mappings during the ontology merging? (All assuming that you're actually using those mappings, and that's the cause of the incorrect equivalence, and that the equivalence is actually incorrect.)

**Comment by cmungall** [comment]
Hi Michael,

Yes, you are correct that the root of this can be traced to the fact 
that Orphanet makes two xrefs with the 'E' category, one to the generic 
form, the other to the AR form.

note that we take a probabilistic approach. We use the orphanet 
e/narrow/broad assignments to boost prior probability. Ideally the best 
globally consistent interpretation of all xrefs is found.

in this case it's not clear why the algorithm didn't make the right 
choice. not only is there other strong evidence pointing to Orphanet:261 
as being equiv, it's globally better. Am investogating...

**Comment by cmungall** [comment]
OK, it turns out there was an edge case with different methods voting for prior probabilities.

With this fixed, the new resolution of this clique looks like this:

![img-orphanet_98855](https://cloud.githubusercontent.com/assets/50745/20999976/054a5142-bccd-11e6-9083-4251ff154317.png)

The thin blue line with p=0.10 between the orphanet AR form and the mesh generic form means that the prior probability was low (since ORDO declares these equiv) yet selecting a subclass interpretation leads to highest combined probability.

not directly related but of note is this edge:

 * Orphanet_98863 X-linked Emery-Dreifuss muscular dystrophy SubClassOf OMIM_300696 Myopathy, X-Linked, With Postural Muscle Atrophy Pr= 0.7068965517241379

**Comment by mwilliamson-healx** [comment]
Great, thanks. When might there be a new release of the Mondo OWL file? (I've also tried generating it myself, but there seemed to be some missing files.)

**Comment by nicolevasilevsky** [comment]
I think this has been addressed, closing
