### ISSUE TITLE
GO import outdated, causing unspecified reasoning behaviour

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-disease-ontology-RETIRED#424]
Same as [closed upheno case](https://github.com/obophenotype/upheno/issues/256), the MONDO GO import (http://purl.obolibrary.org/obo/mondo/imports/go_import.owl) needs to be refreshed: It still uses the old specification of `part of` (which is specified as functional AND transitive, instead of merely transitive). This can cause some issues with reasoning and catapults MONDO (and in turn Monarch.owl) out of the OWL 2 DL profile.

**Comment by cmungall** [comment]
Wow, amazing that one slip in Protege months ago continues to wreak havoc across multiple ontologies like a bull in a semantic china shop! We need @balhoff's atomic ontologies!

And embarrassed the imports are stale. Turns out we were regenerating the imports regularly, but the cached version of the upstream was not being refreshed...
