### ISSUE TITLE
Review classification of X-linked intellectual disability - hypotonic face in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#87]
![image](https://cloud.githubusercontent.com/assets/6722114/15758045/852d3d2e-28bd-11e6-875a-93a81410c134.png)

http://purl.obolibrary.org/obo/Orphanet_93971

**Comment by nicolevasilevsky** [comment]
![image](https://cloud.githubusercontent.com/assets/6722114/16398881/d120e93c-3c82-11e6-8a99-b67e166c01b0.png)

I think the problematic part is with these three terms.

Orphanet_93971 Chudley-Lowry-Hoar syndrome is equiv to OMIM_309580. Both of these Orphanet terms are synonyms of the OMIM term:

SMITH-FINEMAN-MYERS SYNDROME 1; SFM1
SFMS
XLMR-HYPOTONIC FACIES SYNDROME
CARPENTER-WAZIRI SYNDROME
CHUDLEY-LOWRY SYNDROME
JUBERG-MARSIDI SYNDROME; JMS
HOLMES-GANG SYNDROME
MENTAL RETARDATION, X-LINKED, WITH GROWTH RETARDATION, DEAFNESS, AND MICROGENITALISM

So I think Orphanet_93972 is equiv to Orphanet_93971

**Comment by cmungall** [comment]
how it looks in the latest

![img-orphanet_93971](https://cloud.githubusercontent.com/assets/50745/17798490/85d5826c-659f-11e6-90c3-cf9a7b24ac5a.png)

clearly the link with p=0.02 is wrong, should be equivalent. It's being forced to make this due to a high weighting between the ordo and the mesh due to the ordo assignment being E. See #139 - we should downweight these ordo xref categories.

For now we just override it - force equivalence between the mesh and omim with p=1
