### ISSUE TITLE
Review classification of Methylmalonic acidemia with homocystinuria in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#88]
http://purl.obolibrary.org/obo/Orphanet_308380

![image](https://cloud.githubusercontent.com/assets/6722114/15758033/75d51950-28bd-11e6-8f2f-3982ed363668.png)

**Comment by nicolevasilevsky** [comment]
I think the equivalences between these two are correct, based on the synonyms. But should it be stated that OMIM_251100 and MESH_C537360 are probably equiv too?

![image](https://cloud.githubusercontent.com/assets/6722114/15842839/7744e26e-2c11-11e6-86c1-642c7599655b.png)

**Comment by cmungall** [comment]
You could state that, but I don't think this is a particularly problematic part of the graph for the algorithm. The correct interpretation already has the highest weighting for each pair, and in any configuration that has both pairs as being Equiv, we'll get the sideways equivalence via the transitivity of equivalence.

My hunch is that it's having issues with this portion of the graph:

<img width="1149" alt="screen shot 2016-06-06 at 7 24 10 pm" src="https://cloud.githubusercontent.com/assets/50745/15844138/8ef05e24-2c1c-11e6-9c92-3d5210e8a2af.png">

**Comment by nicolevasilevsky** [comment]
Looking at these more closely, I think the three Orphanet terms are all correctly classified, ie, they are equiv to the OMIM term. The OMIM record is really inclusive and includes those three variants.

http://www.omim.org/entry/277410

**Comment by cmungall** [comment]
> Looking at these more closely, I think the three Orphanet terms are all correctly classified, ie, they are equiv to the OMIM term

Note that if this were the case, then all 3 orphanet classes would be equivalent to eachother. We set the probability of this happening as 0. So another solution must be sought.

**Comment by cmungall** [comment]
We now find a solution for this case. Whether it is the correct one or not remains to be seen, the solution forces selection of some edges with low priors.

![img-orphanet_308380](https://cloud.githubusercontent.com/assets/50745/16631772/b449926a-4375-11e6-8bf1-2560a7728c71.png)

**Comment by mellybelly** [comment]
presumably we would expect this on occasion where there is no molecular association and then later they require merging when one is assigned

On Jul 6, 2016, at 12:29 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking at these more closely, I think the three Orphanet terms are all correctly classified, ie, they are equiv to the OMIM term

Note that if this were the case, then all 3 orphanet classes would be equivalent to eachother. We set the probability of this happening as 0. So another solution must be sought.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/monarch-initiative/monarch-disease-ontology/issues/88#issuecomment-230881059>, or mute the thread<https://github.com/notifications/unsubscribe/AAwn3DMT2afOkRtH9CCcKvgRKPyUuiGyks5qTAIqgaJpZM4Is3xd>.

Melissa Haendel, PhD
Associate Professor
Library
Dept. of Medical Informatics and Clinical Epidemiology
haendel@ohsu.edu<mailto:haendel@ohsu.edu>
503-407-5970

**Comment by cmungall** [comment]
In this case I believe it is orphanet's intention to subclass
