### ISSUE TITLE
Review classification of Orphanet_64746 group (CMT/RefSum/Peroxisome/...) in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology-RETIRED#92]
![image](https://cloud.githubusercontent.com/assets/6722114/15757956/0b1bd3b0-28bd-11e6-895c-b6c5d5574318.png)

http://purl.obolibrary.org/obo/MESH_C535417

**Comment by cmungall** [comment]
This is a complex cluster, because we have a lot of interconnected diseases here.

Let's start with ALD. In the most recent run, this cluster succeeded, albeit with low confidence. I am dubious about how adrenoleukodystrophy was resolved. 

It seems the label ALD/adrenoleukodystrophy can be used in two ways: one for the disorder causes specifically by ABCD1, and the other for other peroxisomal disorders with overlapping phenotypes. OMIM uses the label ALD specifically for ABCD1, Orphanet uses it generically, and qualifies with X-linked, neonatal, etc:

 * DOID:10588 adrenoleukodystrophy EquivalentTo [OMIM:300100](http://omim.org/entry/300100) Adrenoleukodystrophy Pr= 0.5421686746987951
 * [OMIM:302700](http://omim.org/entry/302700) Cerebral Sclerosis, Diffuse, Scholz Type SubClassOf [Orphanet:43](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=43) X-linked adrenoleukodystrophy Pr= 0.6885245901639344
 * [OMIM:614871](http://omim.org/entry/614871) Peroxisome Biogenesis Disorder 6B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [OMIM:614920](http://omim.org/entry/614920) Peroxisome Biogenesis Disorder 14B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [DOID:10588](http://purl.obolibrary.org/obo/DOID_10588) adrenoleukodystrophy SubClassOf MESH:D002549 Diffuse Cerebral Sclerosis of Schilder Pr= 0.3516483516483517
 * [OMIM:300100](http://omim.org/entry/300100) Adrenoleukodystrophy SubClassOf [Orphanet:139399](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=139399) Adrenomyeloneuropathy Pr= 0.5
 * [OMIM:614867](http://omim.org/entry/614867) Peroxisome Biogenesis Disorder 5B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [OMIM:614863](http://omim.org/entry/614863) Peroxisome Biogenesis Disorder 4B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * DOID:10588 adrenoleukodystrophy EquivalentTo [Orphanet:59298](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=59298) Schilder disease Pr= 0.6666666666666666
 * [OMIM:300100](http://omim.org/entry/300100) Adrenoleukodystrophy SubClassOf [Orphanet:43](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=43) X-linked adrenoleukodystrophy Pr= 0.7213114754098361
 * [OMIM:614885](http://omim.org/entry/614885) Peroxisome Biogenesis Disorder 11B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [OMIM:266510](http://omim.org/entry/266510) Peroxisome Biogenesis Disorder 3B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [OMIM:601539](http://omim.org/entry/601539) Peroxisome Biogenesis Disorder 1B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [OMIM:300100](http://omim.org/entry/300100) Adrenoleukodystrophy SubClassOf [Orphanet:139396](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=139396) X-linked cerebral adrenoleukodystrophy Pr= 0.25
 * [OMIM:614877](http://omim.org/entry/614877) Peroxisome Biogenesis Disorder 8B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [OMIM:614873](http://omim.org/entry/614873) Peroxisome Biogenesis Disorder 7B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [OMIM:202370](http://omim.org/entry/202370) Peroxisome Biogenesis Disorder 2B SubClassOf [Orphanet:44](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=44) Neonatal adrenoleukodystrophy Pr= 0.5789473684210527
 * [DOID:10588](http://purl.obolibrary.org/obo/DOID_10588) adrenoleukodystrophy EquivalentTo MESH:D000326 Adrenoleukodystrophy Pr= 0.5

**Comment by cmungall** [comment]
What should we do with ones like: [OMIM:302700](http://omim.org/entry/302700) Cerebral Sclerosis, Diffuse, Scholz Type 

"It seems highly probable that Scholz's patients suffered from a form of adrenoleukodystrophy (300100)"

**Comment by cmungall** [comment]
my hyopthesis:

```
0.8 OMIM_300100 Adrenoleukodystrophy SubClassOf DOID_10588 adrenoleukodystrophy
0.8 OMIM_300100 Adrenoleukodystrophy EquivalentTo Orphanet_139396 X-linked cerebral adrenoleukodystrophy
0.8 DOID_10588 adrenoleukodystrophy SiblingOf Orphanet_59298 Schilder disease
0.8 Orphanet_139399 Adrenomyeloneuropathy SubClassOf OMIM_300100 Adrenoleukodystrophy
```

**Comment by cmungall** [comment]
This cluster also links to refsum via peroxisome biogenesis disorders:

 * DOID:10582 Refsum disease EquivalentTo [Orphanet:773](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=773) Refsum disease       0.9473684210526315
 * [DOID:10582](http://purl.obolibrary.org/obo/DOID_10582) Refsum disease EquivalentTo MESH:D012035 Refsum Disease      0.7857142857142857
 * DOID:0050444 infantile refsum disease EquivalentTo [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease 0.75
 * MESH:D052919 Refsum Disease, Infantile EquivalentTo [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease        0.625
 * [OMIM:266500](http://omim.org/entry/266500) Refsum Disease, Classic SubClassOf MESH:D012035 Refsum Disease   0.6029411764705882
 * [OMIM:614867](http://omim.org/entry/614867) Peroxisome Biogenesis Disorder 5B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease  0.5789473684210527
 * [OMIM:614879](http://omim.org/entry/614879) Peroxisome Biogenesis Disorder 9B SubClassOf [Orphanet:773](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=773) Refsum disease     0.5789473684210527
 * [OMIM:614863](http://omim.org/entry/614863) Peroxisome Biogenesis Disorder 4B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease  0.5789473684210527
 * [OMIM:614885](http://omim.org/entry/614885) Peroxisome Biogenesis Disorder 11B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease 0.5789473684210527
 * [OMIM:614873](http://omim.org/entry/614873) Peroxisome Biogenesis Disorder 7B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease  0.5789473684210527
 * [OMIM:614877](http://omim.org/entry/614877) Peroxisome Biogenesis Disorder 8B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease  0.5789473684210527
 * [OMIM:202370](http://omim.org/entry/202370) Peroxisome Biogenesis Disorder 2B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease  0.5789473684210527
 * [OMIM:614920](http://omim.org/entry/614920) Peroxisome Biogenesis Disorder 14B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease 0.5789473684210527
 * [OMIM:266510](http://omim.org/entry/266510) Peroxisome Biogenesis Disorder 3B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease  0.5789473684210527
 * [OMIM:614871](http://omim.org/entry/614871) Peroxisome Biogenesis Disorder 6B SubClassOf [Orphanet:772](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=772) Infantile Refsum disease  0.5789473684210527
 * MESH:D052919 Refsum Disease, Infantile SubClassOf [OMIM:601539](http://omim.org/entry/601539) Peroxisome Biogenesis Disorder 1B      0.5
 * DOID:10582 Refsum disease SubClassOf [OMIM:266510](http://omim.org/entry/266510) Peroxisome Biogenesis Disorder 3B   0.345679012345679

The last one is incorrect

**Comment by cmungall** [comment]
CMT xrefs are causing a lot of problems - for an example, see https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/156

**Comment by pnrobinson** [comment]
http://omim.org/entry/302700 (CEREBRAL SCLEROSIS, DIFFUSE, SCHOLZ TYPE ) is basically a historical entry that has last been updated in the 1960s! The disease that is described here could simply not be accurately diagnosed with the technology available at the time, and thus there is simply no way of knowing whether the family described had a disease that represents a distinct and separate entity. I think that this term should simply be removed.

**Comment by pnrobinson** [comment]
Adrenoleukodystrophy describes several closely related disorders resulting from defects in the metabolism of very-long-chain fatty acids in the nervous system, adrenal gland, and testes.

Peroxisome biogenesis disorder is characterized by the overlapping phenotypes of neonatal adrenoleukodystrophy (NALD) and infantile Refsum disease (IRD), which represent the milder manifestations of the Zellweger syndrome spectrum (ZSS) of peroxisome biogenesis disorders (PBDs). I think there is a spectrum of clinical severity. 

Assertions such as "OMIM:614871 Peroxisome Biogenesis Disorder 6B SubClassOf Orphanet:772 Infantile Refsum disease 0.5789473684210527" are I think going in the wrong direction.

assertions such as "DOID:10582 Refsum disease SubClassOf OMIM:266510 Peroxisome Biogenesis Disorder 3B 0.345679012345679" are taking a general class and making it a subclass of a specific subtype.

I suspect that the problem is that there are no IDs from OMIM, ORDO, or MONDO for things like "Infantile Refsum Disease 6B".

We might want to speak with Ana Rath about working on this cluster together. I think that she might be able to ask somebody in the Orphanet network to think about this.

**Comment by cmungall** [comment]
On 11 Jun 2016, at 0:25, Peter Robinson wrote:

> http://omim.org/entry/302700 (CEREBRAL SCLEROSIS, DIFFUSE, SCHOLZ TYPE 
> ) is basically a historical entry that has last been updated in the 
> 1960s! The disease that is described here could simply not be 
> accurately diagnosed with the technology available at the time, and 
> thus there is simply no way of knowing whether the family described 
> had a disease that represents a distinct and separate entity. I think 
> that this term should simply be removed.

So far we have never removed anything from OMIM in MonDO (there are lots 
of MESH and Orphanet grouping classes we omit, and we merge classes)

This sounds like a case where we should. We can have an auxhiliary 
bridge file where we declare obsolete on classes like this. And we would 
remove these from the annotation file.

**Comment by pnrobinson** [comment]
@drseb  Sebastian, if you agree then we should also have a "blacklist" file for invalid old OMIMentries like this so that they do not get picked up if we ever return to doing semiautomatic knowledge mining from OMIM. I suspect there are about 100 entries in OMIM that basically are not being removed for historical reasons but which really do not help much in the age of genome sequencing.

**Comment by nicolevasilevsky** [comment]
@cmungall is there anything I should do with this one?

**Comment by cmungall** [comment]
Review my commit https://github.com/monarch-initiative/monarch-disease-ontology/commit/4c3352942898aac2227d1d88a79c3a581d95dca8

This helps break the cluster. There is only one problem with the CMT subset (2v):

![img-mesh_c535417](https://cloud.githubusercontent.com/assets/50745/16631294/4d5d724e-4373-11e6-8274-0ed73200782c.png)
